version: "3"
services:

  mysql:
    container_name: check-your-dump-mysql
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - data_mysql:/var/lib/mysql
      - ./data:/home
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - bridge

  phpmyadmin:
    container_name: check-your-dump-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    environment:
      - PMA_HOST=mysql
    networks:
      - bridge

networks:
  bridge:

volumes:
  data_mysql: